blank_issues_enabled: false
contact_links:
  - name: 2by2 Project Telegram 💬
    url: https://t.me/twobytwodiscussion
    about: Be part of our community, ask questions and stay up to date with the latest news.
